#! /bin/sh

sxhkd &
picom &
~/.config/polybar/launch.sh &
nitrogen --restore &
megasync &
redshift -l 44.56923:10.90771 &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          12


bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_motion_interval 50 

# Specific apps settings
bspc rule -a MEGASync state=floating
