--    options = {
--        require("bufferline").setup {
--        diagnostics = "nvim_lsp",
--        color_icons = true, -- whether or not to add the filetype icon highlights
--        get_element_icon = function(element)
--            -- element consists of {filetype: string, path: string, extension: string, directory: string}
--            -- This can be used to change how bufferline fetches the icon
--            -- for an element e.g. a buffer or a tab.
--            -- e.g.
--            local icon, hl = require('nvim-web-devicons').get_icon_by_filetype(filetype, { default = false })
--
--            return icon, hl
--        end,
--        show_buffer_icons = true, -- disable filetype icons for buffers
--    }
--}
