vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>gp", ":Git push -u origin<CR>")
vim.keymap.set("n", "<leader>gd", ":Gdiffsplit!<CR>")
vim.keymap.set("n", "gdh", ":diffget //2<CR>")
vim.keymap.set("n", "gdl", ":diffget //3<CR>")
